### ISSUE TITLE
Analyzer init runs out of memory with many active entities

### ISSUE THREAD

**Issue by jbothma** [pudo/aleph#103]
https://github.com/pudo/aleph/blob/master/aleph/analyze/regex_entity.py#L39

Perhaps in the short term it should be possible to opt out of using the default analyzers?

**Comment by pudo** [comment]
Yep, should add a switch. But how many entities do you have exactly, just out of interest? I got 40k entries here and it's working fine.

**Comment by longhotsummer** [comment]
> select count(1) from entity where state = 'active';
> 148027

Not *that* many, really...

**Comment by jbothma** [comment]
Plus all alternate names? Or are they counted under entities?

**Comment by pudo** [comment]
New config option: ``REGEX_ENTITIES = True``. I've also tried to tune the code of the tagger a little -- the problem is actually just building the automaton, not running it. Got to think about a more space-saving way to do this.
