### ISSUE TITLE
TIKA text extraction doesn't OCR pages that don't have text

### ISSUE THREAD

**Issue by jbothma** [pudo/aleph#104]
This is inconsistent with the default PDFMiner text extraction routine.

This could but doesn't need to use TikaOCR.

I don't have an immediate need for this, just logging the inconsistency and an easy improvement for a willing contributor if we don't have time for it.

**Comment by pudo** [comment]
I've started a page on config options documentation and made a not there, closing here: https://github.com/pudo/aleph/wiki/Configuration
