### ISSUE TITLE
requirements.txt doesn't pin all dependencies

### ISSUE THREAD

**Issue by sihil** [pudo/aleph#130]
Trying to run `1.1` currently doesn't work as the Jinja2 `2.9.x` release has broken the asset management (see https://github.com/miracle2k/webassets/issues/477).

This seems to be a result of some of the dependencies (Jinja2 in this case) not being pinned.

**Comment by stas** [comment]
@sihil we got rid of webassets in #123, but you're right we should pin all possible dependencies. :neutral_face:

**Comment by sihil** [comment]
My colleague tried to bring up using docker-composer on the master branch a couple of weeks ago but that didn't work (for other reasons), so we reverted to using the most recent 'stable' release. Also thrown by two sets of, sometimes conflicting, documentation at http://aleph.readthedocs.io/en/latest/ and https://github.com/pudo/aleph/wiki.

**Comment by stas** [comment]
@sihil http://aleph.readthedocs.io/en/latest/ is the latest documentation. We've migrated and updated most of the wiki (should be pretty much all in fact).

We received two issues recently regarding the installation procedures, but the authors never reported back #125 #126 

Could you tell us what was not working using the latest documentation?

@pudo do you think we could deactivate the wiki for now? The content should not be deleted afaik.

**Comment by sihil** [comment]
The app container doesn't come up cleanly:
```
app_1            | touch aleph/static/style/_custom.scss;
app_1            | (test -f '' && cp -f  aleph/static/style/_custom.scss) || exit 0
app_1            | ./node_modules/webpack/bin/webpack.js --env.prod
app_1            | make: ./node_modules/webpack/bin/webpack.js: Command not found
app_1            | Makefile:14: recipe for target 'assets' failed
app_1            | make: *** [assets] Error 127
```

For users whoa re intending to experiment with aleph, it would be more robust to have a docker-compose that used completely built containers and did not depend on anything build built at startup. Obviously a different use case compared to development. But I'm a few days in and have yet to index any content (the default crawler configured in 1.1 doesn't seem to work and doesn't seem to display or log any errors).

**Comment by stas** [comment]
@sihil I'm sorry you need to get through all of it. Let me see if I can help somehow.

So what you are suggesting is to have a docker-compose file similar to what we have now, but without the local code-base mounted as a [volume]?

@pudo I think this makes sense, I could review what we have now and come up with something.

[volume]: https://github.com/pudo/aleph/blob/master/docker-compose.yml#L50

**Comment by sihil** [comment]
Docker is not my strong point, but yes - I feel like it should be possible to bootstrap aleph using containers that are built as part of a CI pipeline and pushed into a registry. Having said that, my experience of `master` has been better than the errors caused by the unintended Jinja2 upgrade on `1.1`. Still feels brittle at the moment.

**Comment by stas** [comment]
@sihil thank you for all the feedback!
We're still figuring out what's the best way to bootstrap a local dev/prod aleph installation.

**Comment by pudo** [comment]
@sihil thanks for the feedback indeed. We'll need to release a 1.2 soon and make sure it's all pinned, but there's still also some feature work that needs to be rounded off. 

@stas regarding the documentation: having both is sort of the worst case. My very strong preference, given that you've now set up Sphinx, would be to do a last sweep of the wiki and migrate all missing pages to Sphinx, and then shut it down for good. Do you have capacity to look into that, or should I give it a go?

**Comment by stas** [comment]
@pudo as far as I remember I did move most if not all of the content. Please double check, there were some pages related to some custom stuff, just let me know if that needs to be added somewhere to the docs, I'll take care of it.

**Comment by stas** [comment]
@sihil we addressed some of the outstanding issues related to the docker image, but we'd like to take some time and gather some feedback before we introduce some production deployments documentation.

Most likely this will be just a separately provided compose YAML file as it is already mentioned in the [official manual] ([see also]). Any feedback is welcome!

In the meantime I will prepare a separate PR with the requirements pinned up to current versions.

[official manual]: https://docs.docker.com/compose/production/
[see also]: https://github.com/docker/compose/issues/1786

**Comment by pudo** [comment]
I've now pinned all dependencies in requirements.txt which could meaningfully be fixed. Closing.
