### ISSUE TITLE
Date facet navigation/drilldown

### ISSUE THREAD

**Issue by longhotsummer** [pudo/aleph#134]
Hi. Have you guys thought at all about improving the UI for the date facet to support drilldown? eg. year -> month -> day, date ranges, etc.?

kthxbye.

**Comment by pudo** [comment]
There's an issue at #50, but basically, no. Google refine would be my favourite example, even if it means we're going to want to pull in something like D3.

![https://datacandy.github.io/warwick/dataclean/clean11.png](https://datacandy.github.io/warwick/dataclean/clean11.png)

![https://ouseful.files.wordpress.com/2012/11/refine-date-facet.png](https://ouseful.files.wordpress.com/2012/11/refine-date-facet.png)

**Comment by longhotsummer** [comment]
Ah, issue #50, I knew I saw something about it a while ago. Cool, we might look into that if we get a chance. It's a biggie for us.

**Comment by pudo** [comment]
For us, too, unfortunately. Would be amazing to have!
