### ISSUE TITLE
No ingestors found (required setup.py build)

### ISSUE THREAD

**Issue by olethanh** [pudo/aleph#135]
Continuation from #126 

On a fresh install both get_ingestors() and  iter_entry_points('aleph.ingestors') don't return anything.

Steps to reproduce: 

- Fresh install.
- `docker-compose run worker python -c "import pkg_resources; print list(pkg_resources.iter_entry_points('aleph.ingestors'))"`

Running `python setup.py build` inside the container fixed the problem

This should either be done automatically or documented in the installation procedure

**Comment by pudo** [comment]
The thing that drives me crazy about this is that the package is installed via ``pip``, right [here](https://github.com/pudo/aleph/blob/master/Dockerfile#L14). Do you guys understand what the difference between ``python setup.py build`` and ``pip install -e .`` is?
