### ISSUE TITLE
Rename "Watchlist" to "Collection" or "Project"

### ISSUE THREAD

**Issue by pudo** [pudo/aleph#19]
Starting a discussion here, ping @danohuiginn. 

Watchlists are right now meant to be collections of entities that get cross-referenced with the documents in aleph. I'm planning to extend this with additional functionality, such as making the Watchlist/Entity relationships many-to-many and allowing for the de-duplication of entities (currently, our aleph has 5 Bashar Al-Assads).

The next step could be to make Watchlists capable of holding documents as well as entities. This might make sense to allow users to group together documents they're interested in for a particular purpose. However, this is where the name stops making sense. I'd therefore like to propose renaming Watchlists now (before there are too many API dependencies). 

What do you think?

**Comment by pudo** [comment]
Any veto, @danohuiginn ?

**Comment by OpenOilUG** [comment]
Sorry... "not that my original concept"... should read "notE that my
original concept..." :-0 J

On Wed, Mar 23, 2016 at 7:15 PM, Johnny West <johnny.west@openoil.net>
wrote:

> On Collections I would agree - we will shortly probably begin compiling
> collections of documents that fulfil a particular requirement... Not that
> my original concept for the idea of Collections is... curations would have
> been put together by hand specifically to match a particular use case...
>
> We also - separately - want to construct filters for subsets of documents
> that match particular searches... as our instance of Aleph moves towards
> real-time updating (Dan says we are at about 1,000 documents a day now)..
> so that both through push and pull (email and filter links on the
> website)... users could access what are essentially latest results of
> standing queries... or they might constitute API feeds out to other
> websites... but conceptually for me these automated streams are different
> than collections... I also think the ability of users to craft Collections
> for purposes... and comment them (what is your thinking on annotation
> mechanisms?)... could be a significant driver of community and super-use...
>
> Johnny
>
>
>
>
>
>
>
> as we move towards more and more of our document base in Aleph to be in
> real-time
>
> On Fri, Mar 18, 2016 at 10:49 AM, Friedrich Lindenberg <
> notifications@github.com> wrote:
>
>> Starting a discussion here, ping @danohuiginn
>> <https://github.com/danohuiginn>.
>>
>> Watchlists are right now meant to be collections of entities that get
>> cross-referenced with the documents in aleph. I'm planning to extend this
>> with additional functionality, such as making the Watchlist/Entity
>> relationships many-to-many and allowing for the de-duplication of entities
>> (currently, our aleph has 5 Bashar Al-Assads).
>>
>> The next step could be to make Watchlists capable of holding documents as
>> well as entities. This might make sense to allow users to group together
>> documents they're interested in for a particular purpose. However, this is
>> where the name stops making sense. I'd therefore like to propose renaming
>> Watchlists now (before there are too many API dependencies).
>>
>> What do you think?
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pudo/aleph/issues/19>
>>
>
>
>
> --
> Open Oil <http://openoil.net> - Imagine an Open Oil industry
> Most of the world's published oil contracts at a click
> <http://repository.openoil.net/wiki/Main_Page>
> Mapping BP
> <http://www.amazon.com/Mapping-BP-using-track-Corporate-ebook/dp/B00NC1GQ7K/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1415785171&sr=1-1&keywords=mapping+bp>
> - how to mine corporate disclosures
> Author of Karama, Journeys through the Arab Spring
> <http://www.amazon.co.uk/Karama-Journeys-Through-Arab-Spring/dp/0857389947>
> Twitter: @Open_Oil <https://twitter.com/Open_Oil> Skype: delepaak
> Tel: +49 1578 7044286
>
>


-- 
Open Oil <http://openoil.net> - Imagine an Open Oil industry
Most of the world's published oil contracts at a click
<http://repository.openoil.net/wiki/Main_Page>
Mapping BP
<http://www.amazon.com/Mapping-BP-using-track-Corporate-ebook/dp/B00NC1GQ7K/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1415785171&sr=1-1&keywords=mapping+bp>
- how to mine corporate disclosures
Author of Karama, Journeys through the Arab Spring
<http://www.amazon.co.uk/Karama-Journeys-Through-Arab-Spring/dp/0857389947>
Twitter: @Open_Oil <https://twitter.com/Open_Oil> Skype: delepaak
Tel: +49 1578 7044286

**Comment by pudo** [comment]
Johnny, many thanks for that feedback! I'm glad we're agreed on the need for collections and the need for human-curated collections of documents as well as structured information.

On the other idea: that reminds me of iTunes a bit, where you have both Playlists and [Smart Playlists](https://support.apple.com/kb/PH19487?locale=en_US) (which are actually music queries). On a technical level, this is exactly what aleph's alerting system does: store a query from the user and re-activate it when needed (and chop of stuff you saw before). The question is then how to present this to the user: like a normal collection, or, for example, as a selector that would prompt the user to accept or reject smart collection items into a curated collection (an interesting hybrid, perhaps?). 

Finally, on commenting/annotation: I'm just worried that with multiple millions of documents in our systems, such content would get lost. Perhaps it's more interesting to think about notes which connect a particular document to a collection, i.e. justify it's inclusion in the set? In journalism this would be stuff like "This court record proves X knew of Y before he did Z" or "When A bought the company B"....

**Comment by pudo** [comment]
Fixed as of: 096f44254c19f0554bb528a82e3596539c3bd24f
