### ISSUE TITLE
Event triggers | notification alerts

### ISSUE THREAD

**Issue by 4bic** [pudo/aleph#2]
**Use Case**
As a journalist / data importer, I may  want to be alerted of mentions of an an entity in future, so that I can sift through the imported documents incase the entity of interest is missing in the current bunch of documents.

**Comment by pudo** [comment]
Glad to see you're interested in this! Notifications are really high on the list of thing I want to make, ideally some nice HTML formatted emails.

**Comment by pudo** [comment]
This is now implemented: https://github.com/pudo/aleph/tree/master/aleph/alerts
