### ISSUE TITLE
Unable to Get Wb UI of aleph

### ISSUE THREAD

**Issue by danishthanvi1** [pudo/aleph#36]
Hi, 

As i have successfully installed, however unable to figure out. How can I run it's Aleph Web UI for Search.
 
Server Installation Details:
1. Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

2. Aleph, Installation as per the pudo/aleph installation. 
3. Docker and Docker-compose Installation as per the URL. 

Finally:  

root@7748cd87f225:/aleph# aleph runserver
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

Kindly Guide me what are the further dependencies and how can i  get it's Web UI. 

Regards.

**Comment by pudo** [comment]
I think your problem might be ports: if you run aleph using ``aleph runserver`` within a docker container that port will not be exposed unless you specify it to be on the docker command line. Running the docker-compose config file as packaged, you should instead check that the web container is running (via ``docker-compose ps``). If it is, aleph should be exposed on port 13376. If that is publicly exposed on your server, you should be able to open it in a browser, otherwise you'll need to either open it in a firewall or use a reverse proxy to expose it on 80.

**Comment by danishthanvi1** [comment]
Hi, 

Here is the result

ubuntu@ip-172-31-29-217:/srv/aleph$ docker-compose ps
        Name                       Command               State                       Ports
--------------------------------------------------------------------------------------------------------------
aleph_beat_1            celery -A aleph.queue beat ...   Exit 0
aleph_elasticsearch_1   /docker-entrypoint.sh elas ...   Up       9200/tcp, 127.0.0.1:9201->9209/tcp, 9300/tcp
aleph_postgres_1        /docker-entrypoint.sh postgres   Up       127.0.0.1:5439->5432/tcp
aleph_web_1             gunicorn -w 5 -b 0.0.0.0:8 ...   Exit 0
aleph_worker_1          celery -A aleph.queue work ...   Exit 0
aleph_worker_run_5      /bin/bash                        Up
ubuntu@ip-172-31-29-217:/srv/aleph$

Thanks.

**Comment by pudo** [comment]
ok looks like it's all shut off. try ``docker-compose up -d`` :)

**Comment by danishthanvi1** [comment]
here you go. 


ubuntu@ip-172-31-29-217:/srv/aleph$ docker-compose up -d
aleph_postgres_1 is up-to-date
aleph_elasticsearch_1 is up-to-date
Starting aleph_worker_1
Starting aleph_web_1
Starting aleph_beat_1
ubuntu@ip-172-31-29-217:/srv/aleph$ docker-compose ps
        Name                       Command               State                      Ports
-------------------------------------------------------------------------------------------------------------
aleph_beat_1            celery -A aleph.queue beat ...   Up
aleph_elasticsearch_1   /docker-entrypoint.sh elas ...   Up      9200/tcp, 127.0.0.1:9201->9209/tcp, 9300/tcp
aleph_postgres_1        /docker-entrypoint.sh postgres   Up      127.0.0.1:5439->5432/tcp
aleph_web_1             gunicorn -w 5 -b 0.0.0.0:8 ...   Up      0.0.0.0:13376->8000/tcp
aleph_worker_1          celery -A aleph.queue work ...   Up
aleph_worker_run_5      /bin/bash                        Up
ubuntu@ip-172-31-29-217:/srv/aleph$

Thanks.

**Comment by pudo** [comment]
Much better. What happens when you just ``curl http://localhost:13376``. Looks to me like stuff should be alive there.

**Comment by danishthanvi1** [comment]
here is the result. 

ubuntu@ip-172-31-29-217:/srv/aleph$ curl http://localhost:13376

curl: (52) Empty reply from server

**Comment by pudo** [comment]
Ok, weird. You can inspect a container's logs like this: ``docker-compose logs web``.

**Comment by pudo** [comment]
But it seems like a docker config issue to me, perhaps best to study their web site a bit.

**Comment by danishthanvi1** [comment]
Here is the Result,


ubuntu@ip-172-31-29-217:/srv/aleph$ docker-compose logs web
Attaching to aleph_web_1
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS3 Basic User Interface Module" property: 5px auto -webkit-focus-ring-color [1750:3: outline]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: 1px       [3778:3: margin-top]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS3 Basic User Interface Module" property: 5px auto -webkit-focus-ring-color [3804:3: outline]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: 4px       [3962:3: margin-top]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS3 Basic User Interface Module" property: 5px auto -webkit-focus-ring-color [4442:3: outline]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Backgrounds and Borders Module Level 3" property: 4px solid    [4863:3: border-top]
web_1            | ERROR:assets.cssutils:PropertyValue: No match: ('CHAR', u':', 4948, 17)
web_1            | ERROR:assets.cssutils:PropertyValue: Unknown syntax or no value:  progid:DXImageTransform.Microsoft.gradient(enabled = false)
web_1            | ERROR:assets.cssutils:CSSStyleDeclaration: Syntax Error in Property: filter: progid:DXImageTransform.Microsoft.gradient(enabled = false)
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Backgrounds and Borders Module Level 3" property: 4px solid    [5004:3: border-bottom]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -webkit-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent) [6810:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -o-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent) [6811:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent) [6812:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -webkit-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent) [6830:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -o-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent) [6831:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent) [6832:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -webkit-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent) [6841:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -o-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent) [6842:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent) [6843:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -webkit-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent) [6852:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -o-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent) [6853:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent) [6854:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -webkit-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent) [6863:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -o-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent) [6864:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent) [6865:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: start [7890:3: text-align]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: start [8028:3: text-align]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -webkit-linear-gradient(left, rgba(0, 0, 0, 0.5) 0%, rgba(0, 0, 0, 0.0001) 100%) [8283:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -o-linear-gradient(left, rgba(0, 0, 0, 0.5) 0%, rgba(0, 0, 0, 0.0001) 100%) [8284:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: linear-gradient(to right, rgba(0, 0, 0, 0.5) 0%, rgba(0, 0, 0, 0.0001) 100%) [8285:3: background-image]
web_1            | ERROR:assets.cssutils:PropertyValue: No match: ('CHAR', u':', 8287, 17)
web_1            | ERROR:assets.cssutils:PropertyValue: Unknown syntax or no value:  progid:DXImageTransform.Microsoft.gradient(startColorstr='#80000000', endColorstr='#00000000', GradientType=1)
web_1            | ERROR:assets.cssutils:CSSStyleDeclaration: Syntax Error in Property: filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#80000000', endColorstr='#00000000', GradientType=1)
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -webkit-linear-gradient(left, rgba(0, 0, 0, 0.0001) 0%, rgba(0, 0, 0, 0.5) 100%) [8293:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -o-linear-gradient(left, rgba(0, 0, 0, 0.0001) 0%, rgba(0, 0, 0, 0.5) 100%) [8294:3: background-image]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: linear-gradient(to right, rgba(0, 0, 0, 0.0001) 0%, rgba(0, 0, 0, 0.5) 100%) [8295:3: background-image]
web_1            | ERROR:assets.cssutils:PropertyValue: No match: ('CHAR', u':', 8297, 17)
web_1            | ERROR:assets.cssutils:PropertyValue: Unknown syntax or no value:  progid:DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#80000000', GradientType=1)
web_1            | ERROR:assets.cssutils:CSSStyleDeclaration: Syntax Error in Property: filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#80000000', GradientType=1)
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: #000      [8369:3: background-color]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Backgrounds and Borders Module Level 3" property: #982022 1px 0 6px 1px [8885:3: box-shadow]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Box Module Level 3/CSS Level 2.1" property: -moz-scrollbars-vertical [9077:3: overflow]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -webkit-box [9128:3: display]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -webkit-flex [9129:3: display]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: -ms-flexbox [9130:3: display]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: flex [9131:3: display]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: 0.95 [9168:3: font-size]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Box Module Level 3/CSS Level 2.1" property: -moz-scrollbars-vertical [9266:3: overflow]
web_1            | ERROR:assets.cssutils:Property: Invalid value for "CSS Level 2.1" property: text-muted [9348:3: color]
ubuntu@ip-172-31-29-217:/srv/aleph$

**Comment by pudo** [comment]
That (believe it or not :) ) actually looks good: this is the ultra-verbose process of the app's SCSS compiling, which only happens when it's being called successfully. There must be some firewalling issue here, or something with the docker configuration.

**Comment by danishthanvi1** [comment]
sure, I'll check Docker Configuration. Moreover, Once its fixed. 

It should work on URL like:  http://serverip:13376   - -Server IP should be live Server IP Assign. 
Hence no Webserver is required at the moment. 

Thanks.

**Comment by pudo** [comment]
Any progress on this? I'll close the ticket for now unless there's a specific defect in aleph that we can point to. Please feel free to re-open with further details.

**Comment by danishthanvi1** [comment]
hi, 

I have finally managed to get the Aleph UI up and running, 

Here is the URL: http://54.191.176.203:13376/ 

Now i want to perform the following Tasks. 
1. create categories like we see on:  https://data.occrp.org 
2. How to add a domain on Docker so that this IP should be changed. FQDN. 
3. Switch Ports. from 13376 to 80. 
4. SSL Installation. 
5. Do we require any particular installation on Docker. 

Our Architecture is consist on the following Items. 

a. AWS EC2 c4x4 large shared Instance
b.  OS 
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

API Errors:  When we Click on Login it throws Error. how can we fix it. 

Regards.
