### ISSUE TITLE
Error after clicking on login

### ISSUE THREAD

**Issue by danishthanvi1** [pudo/aleph#37]
Hi,

Thanks Once again for all your Help so far!

I have finally managed to get the Aleph UI up and running,

Here is the URL: http://54.191.176.203:13376/

Now i want to perform the following Tasks.
1. create categories like we see on: https://data.occrp.org
2. How to add a domain on Docker so that this IP should be changed. FQDN.
3. Switch Ports. from 13376 to 80.
4. SSL Installation.
5. Do we require any particular installation on Docker.

Our Architecture is consist on the following Items.

a. AWS EC2 c4x4 large shared Instance
b. OS
Distributor ID: Ubuntu
Description: Ubuntu 14.04.4 LTS
Release: 14.04
Codename: trusty

API Errors: When we Click on Login it throws Error. how can we fix it.

Regards.

**Comment by pudo** [comment]
Did you set up valid Google OAuth credentials before attempting to perform OAuth?

**Comment by danishthanvi1** [comment]
Hi, 
No we didn't setup.  Google O Auth Credentials.

**Comment by pudo** [comment]
Closing as it seems to have been missing configuration.
