### ISSUE TITLE
User registration and password-based login

### ISSUE THREAD

**Issue by pudo** [pudo/aleph#52]
@danohuiginn to submit PR :)

**Comment by pudo** [comment]
hey @danohuiginn -- now that aleph.openoil.net has been born to great acclaim, any chance I can tease you into backporting this into master :)

**Comment by longhotsummer** [comment]
Yes please!

**Comment by pudo** [comment]
Note to self: folks at Süddeutsche Zeitung would like to see integration with AD/LDAP here, which should not be too hard once we've got a password prompt in the first place. 

/cc @vwormer

**Comment by stas** [comment]
This should be ready for a review. I'll add LDAP support in a separate branch.

**Comment by stas** [comment]
Both, support for stand-alone users and LDAP support was merged.
I'm closing this.
