### ISSUE TITLE
JS error when merging entities

### ISSUE THREAD

**Issue by jbothma** [pudo/aleph#77]
1. find and accept entities (this one was created by https://github.com/Code4SA/za_entities/blob/master/aleph_za_entities/entities.py)
2. view possible dupes
3. click save
4. observe js error

as at aleph a1b96d7ea290bc7de6db0236482a2bffaf712287
 
![error-merging-entity-dupe](https://cloud.githubusercontent.com/assets/235801/17982263/646770aa-6b07-11e6-88ab-0166afc2ff64.png)

For me this is currently non-urgent

**Comment by pudo** [comment]
Appears to be fixed in ``master``.
