### ISSUE TITLE
Cannot create entity via "/entities POST" API endpoint

### ISSUE THREAD

**Issue by andkamau** [pudo/aleph#86]
To reproduce, POST a payload with name (string), $schema (string), collection_id (array) to `/entities`

API response:   `HTTP/1.1 500 Internal Server Error`
From logs:  `AttributeError("No collection specified.")`

**Comment by pudo** [comment]
I cannot reproduce this issue locally, using the following ``curl`` call (which returns a newly created entity): 

```bash
curl -XPOST -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Authorization: ApiKey xxxx' http://localhost:5000/api/1/entities -d '{"collection_id": [251], "$schema": "/entity/person.json#", "name": "persons-ke"}'
```

I would assume your issue is caused by: a) an authorisation issue, b) using invalid JSON (the thing you pasted me on Slack y'day wasn't JSON). Can you double-check these?

**Comment by andkamau** [comment]
Could not replicate on another environment
