### ISSUE TITLE
ingest slows to a halt after 40 mins to an hour

### ISSUE THREAD

**Issue by jbothma** [pudo/aleph#90]
We're consistently seeing the worker slow down til it produces nothing, while using full CPU. Upgrading psycopg2 doesn't sem to have fixed this as it did in https://github.com/celery/celery/issues/2429

![aleph-deadlock](https://cloud.githubusercontent.com/assets/235801/18699854/264a0882-7fd4-11e6-9704-0b11475d63a6.png)

[celery.log-chunky-monkey-2016-09-21T0813.zip](https://github.com/pudo/aleph/files/484250/celery.log-chunky-monkey-2016-09-21T0813.zip)

chunky-monkey is the hostname

**Comment by jbothma** [comment]
stracing the four worker threads with the most cpu time shows one thread doing nothing, one doing thousands of similar munmap calls a second, one stuck on a futex call for seconds, and one doing wait calls avery second or so.

```
ubuntu@chunky-monkey:~$ sudo strace -p 11654
Process 11654 attached
^CProcess 11654 detached
ubuntu@chunky-monkey:~$ sudo strace -p 11658
Process 11658 attached
futex(0x7f20603472bc, FUTEX_WAIT_PRIVATE, 43, NULL^CProcess 11658 detached
 <detached ...>
ubuntu@chunky-monkey:~$ sudo strace -p 11515
Process 11515 attached
munmap(0x7f2035c76000, 262144)          = 0
munmap(0x7f2035b76000, 262144)          = 0
munmap(0x7f20359b6000, 262144)          = 0
munmap(0x7f20358f6000, 262144)          = 0
munmap(0x7f20356b6000, 262144)          = 0
munmap(0x7f2035536000, 262144)          = 0
munmap(0x7f20353f6000, 262144)          = 0
munmap(0x7f2035036000, 262144)          = 0
...
ubuntu@chunky-monkey:~$ sudo strace -p 10505
Process 10505 attached
select(0, NULL, NULL, NULL, {0, 778061}) = 0 (Timeout)
wait4(115, 0x7f205cb06a8c, WNOHANG, NULL) = 0
wait4(102, 0x7f205cb06a8c, WNOHANG, NULL) = 0
wait4(38, 0x7f205cb06a8c, WNOHANG, NULL) = 0
wait4(15, 0x7f205cb06a8c, WNOHANG, NULL) = 0
select(0, NULL, NULL, NULL, {0, 800000}) = 0 (Timeout)
wait4(115, 0x7f205cb06a8c, WNOHANG, NULL) = 0
wait4(102, 0x7f205cb06a8c, WNOHANG, NULL) = 0
wait4(38, 0x7f205cb06a8c, WNOHANG, NULL) = 0
wait4(15, 0x7f205cb06a8c, WNOHANG, NULL) = 0
```

**Comment by jbothma** [comment]
this shows the rate of work nicely
```
[2016-09-21 06:01:53,125: DEBUG/Worker-1] Extracted 449 characters of text from u'/tmp/54633847e070791687148a1646113c0bf1d9773d-government-gazette-za-vol-597-no-38665-dated-2015-03-31.pdf', p.1
[2016-09-21 06:01:53,192: DEBUG/Worker-1] Extracted 1243 characters of text from u'/tmp/54633847e070791687148a1646113c0bf1d9773d-government-gazette-za-vol-597-no-38665-dated-2015-03-31.pdf', p.2
[2016-09-21 06:01:53,275: DEBUG/Worker-1] Extracted 1535 characters of text from u'/tmp/54633847e070791687148a1646113c0bf1d9773d-government-gazette-za-vol-597-no-38665-dated-2015-03-31.pdf', p.3
[2016-09-21 06:09:15,873: DEBUG/Worker-19] Extracted 4090 characters of text from u'/tmp/54633847e070791687148a1646113c0bf1d9773d-government-gazette-za-vol-597-no-38665-dated-2015-03-31.pdf', p.50
[2016-09-21 06:16:09,679: DEBUG/Worker-19] Extracted 3721 characters of text from u'/tmp/54633847e070791687148a1646113c0bf1d9773d-government-gazette-za-vol-597-no-38665-dated-2015-03-31.pdf', p.51
[2016-09-21 06:17:27,988: DEBUG/Worker-1] Extracted 4767 characters of text from u'/tmp/54633847e070791687148a1646113c0bf1d9773d-government-gazette-za-vol-597-no-38665-dated-2015-03-31.pdf', p.4
[2016-09-21 06:18:46,221: DEBUG/Worker-1] Extracted 4754 characters of text from u'/tmp/54633847e070791687148a1646113c0bf1d9773d-government-gazette-za-vol-597-no-38665-dated-2015-03-31.pdf', p.5
[2016-09-21 06:20:45,320: DEBUG/Worker-19] Extracted 4340 characters of text from u'/tmp/54633847e070791687148a1646113c0bf1d9773d-government-gazette-za-vol-597-no-38665-dated-2015-03-31.pdf', p.52
```

**Comment by pudo** [comment]
Just for my entertainment: could you (for a test) remove the PDF parsing code entirely (not just OCR, but ``pdf.py:extract_pdf`` -- replace it with sleep(2) and see if the issue persists?

**Comment by jbothma** [comment]
@pudo If I do that in production, what will those ingested docs look like? Sounds like something I' do on a test database, right?

**Comment by pudo** [comment]
You should return ``{"pages": {}}`` which will simply generate empty document stubs.

**Comment by jbothma** [comment]
Sure - will try in a bit. First want to figure out how to use gdp to pinpoint where things are blocking if that's possible

**Comment by pudo** [comment]
That sounds more systematic than what I was proposing. Keep me up to date!

**Comment by jbothma** [comment]
I couldn't get much out of dbg. Greg pointed me in the right direction, checking whether workers really restarted. All of them except one had restarted. Other worker IDs in recent lgs were 6, 19 and 17. Worker 1 was still there despite CELERYD_MAX_TASKS_PER_CHILD=5. I killed all the worker processes with `kill -9` and suddenly new workers span up and started getting work done.

I've changed CELERYD_MAX_TASKS_PER_CHILD to 1 now to make really sure that it restarts and cleans itself up often. I'll leave it for an hour and if it's still productive I'll leave it like this.

I don't have time to run the test removing pdf processing right now - it'd mean disabling my laptop or setting up a new machine so it'll have to wait for less pressing time. It sounds like an interesting avenue since one of the initial workers must have been upset by some of the work it had done and it'd be interesting if pdfminer is related to this. Running this test on a new machine will involve around 2 hours - one hour to reproduce the stalling and another hour to see whether stalling happens without the pdf text extraction.

To get through my current ingest backlog I'll just make restart the entire worker node with cron every 30 mins or so to get through the bulk and incremental-crawl til everything's in until we understand this better.

I've removed newrelic from the app and this is still happening so that's ruled out.

This is what resource usage looks like. Around 7PM GMT+2 is when I got memory usage under control and around 10PM GMT+2 is when I left it for the night.
![new-relic-chunky-monkey](https://cloud.githubusercontent.com/assets/235801/18704027/917e8f74-7fe8-11e6-994f-ee5d6f54c5b3.png)

This is the rate at which documents are being ingested and analysed
```SQL
select date_trunc('hour', created_at) as hour, count(*) from document  group by date_trunc('hour', created_at) order by hour desc;
```
```
        hour         | count 
---------------------+-------
 2016-09-21 08:00:00 |    29
 2016-09-21 06:00:00 |     1
 2016-09-20 22:00:00 |     1
 2016-09-20 21:00:00 |    11
 2016-09-20 20:00:00 |    35
 2016-09-20 19:00:00 |    57
 2016-09-20 18:00:00 |    57
```

I'm curious to hear whether others have experienced the same slowdown over time.

**Comment by jbothma** [comment]
NB this is running this branch https://github.com/pudo/aleph/pull/89/commits/91387c3ff8172fb99b466eff0a00671eecff5fab

it could be related to the different way of creating celery app instances although I was seeing this behaviour before on pudo/aleph master

**Comment by jbothma** [comment]
it got stuck again so it looks like I'll have to go with a cron restart - for some reason it's not sufficient for celery to restart the workers - it only gets fast again when I kill the processes from the OS and let celery start them again

**Comment by jbothma** [comment]
I'm now quite sure this wasn't any weird concurrency or buffer issue at all, just pdfminer that has a very inefficient way of iterating over text boxes which I think is exponential with the number of text boxes in a page.

It's now chewing through gazettes without slowdown on https://github.com/pudo/aleph/pull/91 (on a single thread because it was running out of memory with 4 threads) - the remaining documents in the ingest queue are the pathological examples - e.g. maps or tables with horizontal text where the PDF has one or two characters per text box.
```
 2016-09-26 18:00:00 |    48
 2016-09-26 17:00:00 |    41
 ```

**Comment by jbothma** [comment]
@pudo figured it out, I just saw it in a stacktrace and understood :)

**Comment by pudo** [comment]
This is brilliant news, something I'd suspected but was unable to show well enough. I'm currently getting a bit mixed up in pdfminer development because I think that it must somehow be possible to do PDF text extraction in pure Python (https://github.com/euske/pdfminer/pull/71). Still, if we fail to convince the pdfminer maintainer to open up development and allow for bug fixes, Tika should probably become the default. 

Should we close this?

**Comment by jbothma** [comment]
Yeah seems to be working fine for us with Tika with multiple workers and
consistent continuous operation. Can re-open if something like this comes
up again.
