### ISSUE TITLE
Hidden collections show up in "Document collections" list

### ISSUE THREAD

**Issue by longhotsummer** [pudo/aleph#92]
Collections that aren't visible to the public still show up in the "Document collections" list for a search. This happens even though the ES query is scoped to only the collections the user can see. My guess is this is because a document is in multiple collections, so the filter matches successfully on a visible collection ID, but the aggregation happens on all collections for a document, even ones the user can't see.

**Comment by pudo** [comment]
Thanks for reporting, this sounds severe. I assume it could be fixed by explicitly filtering the facet down to the queryable collections, will give it a look this afternoon!

**Comment by longhotsummer** [comment]
I don't see how we can do this at the ES level, without explicitly listing the non-visible collections as a "must_not" agg, which seems a bit backwards.

How about filtering the returned aggregate buckets after ES, in api.search.documents.execute_documents_query.

**Comment by pudo** [comment]
Fair enough, as long as there's no limit on the collections anyway. I guess in ``facets.py:convert_collections`` such a check would be trivial to add. Quick fix :)

**Comment by longhotsummer** [comment]
Candidate patch in https://github.com/pudo/aleph/pull/94
