### ISSUE TITLE
App title not set correctly when page first rendered

### ISSUE THREAD

**Issue by longhotsummer** [pudo/aleph#95]
There's a race condition in https://github.com/pudo/aleph/blob/master/aleph/static/js/services/Title.js -- the page title is set before the metadata is loaded. Once the metadata is loaded and appTitle is up to date, the page title isn't re-rendered until the whole page changes.

I'm not sufficiently familiar with Angular to know how to trigger a re-render when appTitle changes.

**Comment by pudo** [comment]
Fixed in 0762ac4eb4ac840072188b324941c316c83e3a9f
